apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
    name: "{{ template "fullname" . }}-ingress"
    annotations:
        kubernetes.io/ingress.class: "voyager"
        #ingress.appscode.com/stats: "true"
        #ingress.appscode.com/stats-port: "1936"
        #ingress.appscode.com/stats-secret-name: basicauth
        #ingress.appscode.com/default-timeout: '{"connect": "5s", "client": "5m", "server": "1d"}'
        #ingress.appscode.com/max-connections: "10000"
      {{- if .Values.ingressIP }}
        ingress.appscode.com/load-balancer-ip: {{ .Values.ingressIP }}
      {{- end }}
spec:
  {{- if (.Values.tls.host) and .Values.tls.refName }}
    tls:
        -   hosts:
                - "{{ .Values.tls.host }}"
                - "backend.{{ .Values.tls.host }}"
                - "ht.{{ .Values.tls.host }}"
                - "couch.{{ .Values.tls.host }}"
            ref:
                kind: Secret
                name: {{ .Values.tls.refName }}
    frontendRules:
        -   port: 443
            rules:
                - option httplog
                - option forwardfor
                - http-request set-header X-Forwarded-Proto https
  {{- end }}
    rules:
        -   host: "ht.{{ .Values.tls.host }}"
            http:
                paths:
                    -   path: /
                        backend:
                            serviceName: "{{ template "fullname" . }}-frontend"
                            servicePort: {{ .Values.images.frontend.servicePort }}
        -   host: "backend.{{ .Values.tls.host }}"
            http:
                paths:
                    -   path: /
                        backend:
                            serviceName: "{{ template "fullname" . }}-backend"
                            servicePort: {{ .Values.images.backend.servicePort }}
        -   host: "{{ .Values.tls.host }}"
            http:
                paths:
                    -   path: /
                        backend:
                            serviceName: "{{ template "fullname" . }}-backend"
                            servicePort: {{ .Values.images.backend.servicePort }}

        -   host: "couch.{{ .Values.tls.host }}"
            http:
                paths:
                    -   path: /
                        backend:
                            serviceName: {{ .Values.couchdbServiceName }}
                            servicePort: {{ .Values.couchdbPortNumber }}
                            backendRules:
                                - 'option httpchk GET /_up HTTP/1.0\r\nAuthorization:\ Basic\ {{ .Values.couchdbCredentialsBase64 }}'